name: calibre-musl-amd64-update

on:
  push:
    paths:
      - '.github/workflows/calibre-musl-amd64-update.yml'
  workflow_dispatch:

env:
  CALIBRE_VER: 8.0.1
  CALIBRE_DEP_VER: 8.0.1

jobs:
  job1:
    name: build_calibre
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: build_x86_64
        run: |
          sudo apt-get update
          sudo apt-get install  python3 qemu-user-static
          cd /home/runner/work/bypy/
          wget  https://download.calibre-ebook.com/${{ env.CALIBRE_VER}}/calibre-${{ env.CALIBRE_VER}}.tar.xz
          cp -rf /home/runner/work/bypy/ /home/runner/work/bypy.bak
          wget -P /home/runner/work  https://github.com/gshang2017/bypy/releases/download/v${{ env.CALIBRE_DEP_VER}}/calibre-${{ env.CALIBRE_DEP_VER}}-x86_64_dep.tar.gz
          tar -xJf calibre-${{ env.CALIBRE_VER}}.tar.xz
          mv calibre-${{ env.CALIBRE_VER}} calibre
          tar xzPf /home/runner/work/calibre-${{ env.CALIBRE_DEP_VER}}-x86_64_dep.tar.gz
          cp -rf /home/runner/work/bypy/bypy/calibre.patch/*  /home/runner/work/bypy/calibre
          sed -i  s/readonly=True/readonly=False/g  /home/runner/work/bypy/bypy/bypy/linux.py
          sed -i  s/aarch64/x86_64/g  /home/runner/work/bypy/calibre/bypy/linux/__main__.py
          mkdir -p /home/runner/work/bypy/calibre/bypy/b/linux/64/chroot
          cd /home/runner/work/bypy/calibre
          sudo python3 setup.py linux64
          sudo mv /home/runner/work/bypy/calibre/dist/calibre-${{ env.CALIBRE_VER}}-x86_64.musl.txz /home/runner/work/bypy/calibre/dist/calibre-${{ env.CALIBRE_VER}}-x86_64.musl.txz.original

      - name: build_x86_64_modify.env
        run: |
          cd /home/runner/work/bypy/calibre
          echo -e "\nimport re\r#https://github.com/snomiao/calibre-utf8-path\r# 定义文件名转换函数\rdef re_filename(filename):\r    if len(filename) > 80:\r       filename = filename[0:80]\r# 替换为空\r    return re.sub(r\"[\/\\\\\\\\\\:\*\?\\\"\<\>\|\\\\0]\", \"\", filename)\r"   >> src/calibre/db/backend.py
          sed -i s/"author = ascii_filename(author"/"    author = ascii_filename(author"/g   src/calibre/db/backend.py
          sed -i s/"title  = ascii_filename(title"/"    title  = ascii_filename(title"/g   src/calibre/db/backend.py
          sed -i "/author = ascii_filename(author/i\        ascii_filename_set = os.environ.get('CALIBRE_ASCII_FILENAME', 'true')" src/calibre/db/backend.py
          sed -i "/author = ascii_filename(author/i\        if ascii_filename_set == 'false':" src/calibre/db/backend.py
          sed -i "/author = ascii_filename(author/i\            author = re_filename(author)[:l]" src/calibre/db/backend.py
          sed -i "/author = ascii_filename(author/i\            title  = re_filename(title.lstrip())[:l].rstrip()" src/calibre/db/backend.py
          sed -i "/author = ascii_filename(author/i\        else:" src/calibre/db/backend.py
          sudo python3 setup.py linux64
          sudo mv /home/runner/work/bypy/calibre/dist/calibre-${{ env.CALIBRE_VER}}-x86_64.musl.txz /home/runner/work/bypy/calibre/dist/calibre-${{ env.CALIBRE_VER}}-x86_64.modify.env.musl.txz
          sudo mv /home/runner/work/bypy/calibre/dist/calibre-${{ env.CALIBRE_VER}}-x86_64.musl.txz.original /home/runner/work/bypy/calibre/dist/calibre-${{ env.CALIBRE_VER}}-x86_64.musl.txz

      - name: 'build_calibre_x86_64_dep.tar.gz'
        run: |
          tar -czPf /home/runner/work/bypy/calibre-${{ env.CALIBRE_VER}}-x86_64_dep.tar.gz /home/runner/work/bypy/calibre/bypy/b/linux/64/sw/pkg

      - name: Create Release x86_64
        id: create_release_x86_64
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          tag: v${{ env.CALIBRE_VER}}
          name: version ${{ env.CALIBRE_VER}}
          body: |
            alpine: calibre-version-${{ env.CALIBRE_VER}} modify.env版支持中文目录书库需设定环境变量(CALIBRE_ASCII_FILENAME=false)
          draft: false
          prerelease: false
          artifacts: "/home/runner/work/bypy/calibre-${{ env.CALIBRE_VER}}-x86_64_dep.tar.gz,/home/runner/work/bypy/calibre/dist/calibre-${{ env.CALIBRE_VER}}-x86_64.musl.txz,/home/runner/work/bypy/calibre/dist/calibre-${{ env.CALIBRE_VER}}-x86_64.modify.env.musl.txz"

      - name: update tag
        id: update_tag
        uses: richardsimko/update-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.CALIBRE_VER}}
          name: version ${{ env.CALIBRE_VER}}
